---
title: "hw3_part2"
output: html_document
---
#TFIDF
##資料整理
```{r}
library(tm)
library(tmcn)
library(Matrix)
library(wordcloud)
library(ggplot2)
library(varhandle)
library(scales)
library(dygraphs)
library(xts)
library(factoextra)
```

```{r}
docs <- readLines("./DATA/01.txt")
docs <- readLines("./DATA/02.txt")
docs <- readLines("./DATA/03.txt")
docs <- readLines("./DATA/04.txt")
docs <- readLines("./DATA/05.txt")
docs <- readLines("./DATA/06.txt")

```

#Term-Document Matrix
```{r}
##將txt檔匯入成corpus檔
docs.corpus <- Corpus(VectorSource(docs))
##將corpus檔斷詞
docs.seg <- tm_map(docs.corpus, segmentCN)
##斷詞後轉成tdm檔
docs.tdm <- TermDocumentMatrix(docs.seg, control = list())
inspect(docs.tdm)
```

#TFIDF Counting
```{r}
##計算每個詞的term frequency
docs.tf <- apply(as.matrix(docs.tdm), 2, function(doc) {doc / sum(doc)})
##定義計算idf的function
idf.function <- function(word_doc) { log2( (length(word_doc)+1) / nnzero(word_doc) ) }
##計算idf
docs.idf <- apply(docs.tdm, 1, idf.function)
##tfidf = tf*idf
docs.tfidf <- docs.tf * docs.idf
head(docs.tfidf)
```

#Wordcloud
```{r}
f <- sort(rowSums(docs.tfidf), decreasing = T)
docs.df <- data.frame(
  word = names(f),
  freq = f )
wordcloud(docs.df$word, docs.df$freq, scale=c(15,0.1),min.freq=20,max.words=50, colors=brewer.pal(10, "Paired"))
```





###According to TFIDF Counting & Wordcloud:
####賈寶玉&林黛玉明明是紅樓夢的主角,但是在前6章好像不太重要,反而劉姥姥戲份那麼重,之前都沒注意到

#PCA
```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)
```

```{r}
fviz_eig(docs.pca)
```

```{r}
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
```

```{r}
fviz_pca_var(docs.pca, col.var = "contrib")
```

```{r}
fviz_pca_biplot(docs.pca, geom.ind = "point")
```
#PCA results
```{r}
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)
```

#K-means
#Choosing K
```{r}
ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")
```

#Clustering
```{r}
km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
```





##學習紀錄
###Query of Words & temp graph堅持好久還是沒畫出來好傷心.再接再厲